<?php
/**
 * Serves /llms.txt - an AI-friendly index of the site (the emerging llms.txt
 * standard). Just as robots.txt guides crawlers, llms.txt tells LLMs/AI answer
 * engines what this site is about and which pages matter, in clean markdown, so
 * they understand and cite the site better (GEO/AEO).
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class WPPSEO_LLMs {

	private static $instance = null;
	const SLUG = 'llms.txt';

	public static function instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	private function __construct() {
		add_action( 'init', array( __CLASS__, 'add_rewrite' ) );
		add_filter( 'query_vars', array( $this, 'query_var' ) );
		add_action( 'template_redirect', array( $this, 'maybe_render' ) );
	}

	public static function add_rewrite() {
		add_rewrite_rule( '^' . self::SLUG . '$', 'index.php?wppseo_llms=1', 'top' );
	}

	public function query_var( $vars ) {
		$vars[] = 'wppseo_llms';
		return $vars;
	}

	public function maybe_render() {
		if ( ! get_query_var( 'wppseo_llms' ) ) {
			return;
		}
		header( 'Content-Type: text/plain; charset=UTF-8' );

		$name = get_bloginfo( 'name' );
		$desc = get_bloginfo( 'description' );

		// If the owner (or the AI) set a custom llms.txt, serve that verbatim.
		$custom = get_option( 'wpps_llms_txt', '' );
		if ( is_string( $custom ) && trim( $custom ) !== '' ) {
			echo $custom; // phpcs:ignore WordPress.Security.EscapeOutput
			exit;
		}

		// Otherwise auto-generate from the site.
		echo '# ' . $name . "\n\n";
		if ( $desc ) {
			echo '> ' . $desc . "\n\n";
		}
		echo 'Website: ' . home_url( '/' ) . "\n\n";

		// Key pages.
		$pages = get_pages( array( 'sort_column' => 'menu_order', 'number' => 30 ) );
		if ( $pages ) {
			echo "## Pages\n\n";
			foreach ( $pages as $pg ) {
				$excerpt = wp_strip_all_tags( get_the_excerpt( $pg ) );
				$excerpt = $excerpt ? ': ' . wp_trim_words( $excerpt, 20 ) : '';
				echo '- [' . $pg->post_title . '](' . get_permalink( $pg ) . ')' . $excerpt . "\n";
			}
			echo "\n";
		}

		// Recent posts (most useful/citable content).
		$q = new WP_Query( array(
			'post_type'      => 'post',
			'post_status'    => 'publish',
			'posts_per_page' => 100,
			'orderby'        => 'modified',
			'order'          => 'DESC',
			'no_found_rows'  => true,
		) );
		if ( $q->have_posts() ) {
			echo "## Articles\n\n";
			while ( $q->have_posts() ) {
				$q->the_post();
				$excerpt = wp_strip_all_tags( get_the_excerpt() );
				$excerpt = $excerpt ? ': ' . wp_trim_words( $excerpt, 20 ) : '';
				echo '- [' . get_the_title() . '](' . get_permalink() . ')' . $excerpt . "\n";
			}
			wp_reset_postdata();
			echo "\n";
		}

		echo '---' . "\n";
		echo 'Generated by wptaskify. Sitemap: ' . home_url( '/' . WPPSEO_Sitemap::SLUG ) . "\n";
		exit;
	}
}
